# Common interfaces

interface Equipment {
  id: ID!
  name: String!
  webid: String
  parent: String
  description: String
  position_x: Float
  position_y: Float
}

# Specific Types with Attributes
type StorageTank implements Equipment {
  id: ID!
  name: String!
  webid: String
  parent: String
  description: String
  position_x: Float
  position_y: Float
  capacity: String
  contents: String
}

type Separator implements Equipment {
  id: ID!
  name: String!
  webid: String
  parent: String
  description: String
  position_x: Float
  position_y: Float
  inputs: [String!]
  outputs: [String!]
  pressure: String
  temperature: String
  separation_efficiency: Float
}

type Query {
  equipment(id: ID!): Equipment
  allEquipment: [Equipment!]!
  execute: String
}

type Mutation {
  updateEquipmentStatus(id: ID!, status: String!): Equipment
}

type Subscription {
  equipmentUpdated: Equipment
}
